### ISSUE TITLE
토큰을 가진 유저가 채널을 leave했을 때 메세지 생성 오류

### ISSUE THREAD

**Issue by hqafqd** [ACupofCommit/anonymouslack#26]
토큰을 가진 유저가 채널에서 leave 해서
그  채널에 더이상 token을 가지고 있는 유저가 없을 때,

채널에 남아있는 유저가
기존에 포스트된 메세지에서
익명 메세지 작성을 시도하거나  댓글 작성을 시도 했을 때 에러 발생.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
v2에서 granular permissions 을 적용한 bot을 사용하여 해결.
